// Generated by asm2c https://github.com/frranck/asm2c
#ifndef MRBOOM_H__
#define MRBOOM_H__
// /opt/retropie/emulators/retroarch/bin/retroarch -L ./lodsb_libretro.so
// sudo swapon -a
// qemu-system-ppc  -hda ./debian_wheezy_powerpc_standard.qcow2  -L bios -m 1G -g 1024x768x8 -net user,hostfwd=tcp::10022-:22 -net nic

#include <stdint.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <math.h>
#include <setjmp.h>
#include <stddef.h>
#include <stdio.h>

#if defined(_WIN32) || defined(__INTEL_COMPILER)
#define INLINE __inline
#elif defined(__STDC_VERSION__) && __STDC_VERSION__>=199901L
#define INLINE inline
#elif defined(__GNUC__)
#define INLINE __inline__
#else
#define INLINE
#endif

/**
 * is_little_endian: 
 *
 * Checks if the system is little endian or big-endian.
 *
 * Returns: greater than 0 if little-endian,
 * otherwise big-endian.
 **/
static INLINE uint8_t is_little_endian(void)
{
#if defined(__x86_64) || defined(__i386) || defined(_M_IX86) || defined(_M_X64)
    return 1;
#elif defined(MSB_FIRST)
    return 0;
#else
    union
    {
        uint16_t x;
        uint8_t y[2];
    } u;
    
    u.x = 1;
    return u.y[0];
#endif
}


#define realAddress(offset,segment) ((db *)&m+(dd)offset+m.selectors[m.segment])

#define db unsigned char
#define dw unsigned short
#define dd unsigned int

#define VGARAM_SIZE 320*200
#define STACK_SIZE 1024*sizeof(dd)
#define HEAP_SIZE 1024*1024*4
#define NB_SELECTORS 128

#define PUSHAD memcpy (&m.stack[m.stackPointer], &m.eax, sizeof (dd)*8);m.stackPointer+=sizeof(dd)*8
#define POPAD m.stackPointer-=sizeof(dd)*8;memcpy (&m.eax, &m.stack[m.stackPointer], sizeof (dd)*8)

#define PUSH(nbBits,a) memcpy (&m.stack[m.stackPointer], &a, sizeof (a));m.stackPointer+=sizeof(a)
#define POP(nbBits,a) m.stackPointer-=sizeof(a);memcpy (&a, &m.stack[m.stackPointer], sizeof (a))

#define AFFECT_ZF(a) m.ZF=(a==0)
#define AFFECT_CF(a) m.CF=a
#define AFFECT_SF(nbBits, a) m.SF=(a>>(nbBits-1))
#define ISNEGATIVE(nbBits,a) (a & (1 << (nbBits-1)))

// TODO: add missings affected flags on CMP
#define CMP(nbBits,a,nbBitsSrc,b) AFFECT_ZF(a-b);AFFECT_CF(a<b);AFFECT_SF(nbBits,(a-b));
#define OR(nbBits,a,nbBitsSrc,b) a=a|b;AFFECT_ZF(a);AFFECT_SF(nbBits, a)
#define XOR(nbBits,a,nbBitsSrc,b) a=a^b;AFFECT_ZF(a);AFFECT_SF(nbBits, a)
#define AND(nbBits,a,nbBitsSrc,b) a=a&b;AFFECT_ZF(a);AFFECT_SF(nbBits, a)
#define NEG(nbBits,a) AFFECT_CF(a!=0);a=-a;
#define TEST(nbBits,a,nbBitsSrc,b) AFFECT_ZF((a&b));AFFECT_CF(b<a);AFFECT_SF(nbBits, (a&b))

#define SHR(nbBits,a,nbBitsSrc,b) a=a>>b
#define SHL(nbBits,a,nbBitsSrc,b) a=a<<b
#define ROR(nbBits,a,nbBitsSrc,b) a=(a>>b | a<<(nbBits-b))
#define ROL(nbBits,a,nbBitsSrc,b) a=(a<<b | a>>(nbBits-b))

#define READDDp(a) ((dd *) &m.a)
#define READDWp(a) ((dw *) &m.a)
#define READDBp(a) ((db *) &m.a)

#define READDD(a) (*(dd *) &m.a)

// TODO: fix for little endian

//#define READDW(a) (*(dw *) &m.a)
#define READDW(a) (*(dw *)(((db *) &m.a)+(is_little_endian()?0:(sizeOf ## a==2?0:2))))
#define READDBh(a) (*(((db *) &m.a)+(is_little_endian()?1:(sizeOf ## a==2?0:2))))
#define READDBl(a) (*(((db *) &m.a)+(is_little_endian()?0:(sizeOf ## a==2?1:3))))

#define READDBhW(a) (*(((db *) &m.a)+(is_little_endian()?1:0)))
#define READDBhD(a) (*(((db *) &m.a)+(is_little_endian()?1:2)))
#define READDBlW(a) (*(((db *) &m.a)+(is_little_endian()?0:1)))
#define READDBlD(a) (*(((db *) &m.a)+(is_little_endian()?0:3)))


//#define WRITEDDWreg(a,b) m.a = (m.a & 0xffffffffffff0000) | b

#define ADD(nbBits,a,nbBitsSrc,b) a=a+b;AFFECT_ZF(a);AFFECT_CF(a<b);AFFECT_SF(nbBits,a);
#define SUB(nbBits,a,nbBitsSrc,b) a=a-b;AFFECT_ZF(a);AFFECT_CF(b<a);AFFECT_SF(nbBits,a);

// TODO: should affects OF, SF, ZF, AF, and PF
#define INC(nbBits,a) a=a+1;AFFECT_ZF(a)
#define DEC(nbBits,a) a=a-1;AFFECT_ZF(a)

#define JE(label) if (m.ZF) GOTOLABEL(label)
#define JZ(label) JE(label)

#define JNE(label) if (!m.ZF) GOTOLABEL(label)
#define JNZ(label) JNE(label)

#define JNB(label) if (!m.CF) GOTOLABEL(label)
#define JAE(label) JNB(label)
#define JNC(label) JNB(label)

#define JB(label) if (m.CF) GOTOLABEL(label)
#define JC(label) JB(label)
#define JNAE(label) JB(label)

#define JA(label) if (!m.CF && !m.ZF) GOTOLABEL(label)
#define JNBE(label) JA(label)

#define JS(label) if (m.SF) GOTOLABEL(label)
#define JNS(label) if (!m.SF) GOTOLABEL(label)

#define JNA(label) if (m.CF || m.ZF) GOTOLABEL(label)
#define JBE(label) JNA(label)

#define MOV(nbBits,dest,nbBitsSrc,src) dest = src
#define MOVZX(nbBits,dest,nbBitsSrc,src) dest = src
#define MOVSX(nbBits,dest,nbBitsSrc,src) if ISNEGATIVE(nbBitsSrc,src) { dest = ((-1 ^ (( 1 <<nbBitsSrc )-1)) | src ); } else { dest = src; }

// LEA - Load Effective Address
#define LEA(nbBits,dest,nbBitsSrc,src) dest = src

// MOVSx (DF FLAG not implemented)
#define MOVS(a,ecx) src=realAddress(m.esi,ds);dest=realAddress(m.edi,es); \
if (labs(((char *)dest)-((char *)src))<=a) { \
    for(int i=0;i<ecx;i++) {  \
        src=realAddress(m.esi,ds);dest=realAddress(m.edi,es); \
        memmove(dest,src,a);m.edi+=a;m.esi+=a; } \
} else { \
    memmove(dest,src,a*ecx);m.edi+=a*ecx;m.esi+=a*ecx; \
}

#define MOVSB MOVS(1,1)
#define MOVSW MOVS(2,1)
#define MOVSD MOVS(4,1)

#define REP_MOVS(b) MOVS(b,m.ecx)
#define REP_MOVSB REP_MOVS(1)
#define REP_MOVSW REP_MOVS(2)
#define REP_MOVSD REP_MOVS(4)

#define STOS(a) memcpy (realAddress(m.edi,es), &m.eax, a);m.edi+=a
#define STOSB STOS(1)
#define STOSW STOS(2)
#define STOSD STOS(4)

#define REP_STOSB for (int i=0;i<m.ecx;i++) { STOSB; }
#define REP_STOSW for (int i=0;i<m.ecx;i++) { STOSW; }
#define REP_STOSD for (int i=0;i<m.ecx;i++) { STOSD; }

#define LODS(a,b) memcpy (((db *)&m.eax)+b, realAddress(m.esi,ds), a);m.esi+=a
#define LODSB LODS(1,(is_little_endian()?0:3))
#define LODSW LODS(2,(is_little_endian()?0:2))
#define LODSD LODS(4,0)

#define REP_LODS(a) memcpy (&m.eax, realAddress(m.esi,ds), m.ecx*a);m.esi+=m.ecx*a
#define REP_LODSB REP_LODS(1)
#define REP_LODSW REP_LODS(2)
#define REP_LODSD REP_LODS(4)

// JMP - Unconditional Jump
#define JMP(label) GOTOLABEL(label)
#define GOTOLABEL(a) goto a

#ifndef DEBUG
#define R(a) a
#else
#define R(a) printf("l:%d:%s\n",__LINE__,#a);a
#endif

#define LOOP(label) DEC(32,m.ecx);JNZ(label)

#define CLD m.DF=0
#define STD m.DF=1

void stackDump();
void hexDump (void *addr, int len);
void asm2C_INT(int a);

#define INT(a) asm2C_INT(a);TESTJUMPTOBACKGROUND

#define TESTJUMPTOBACKGROUND  if (m.jumpToBackGround) { CALL(moveToBackGround) };

void asm2C_OUT(int16_t address, int data);
#define OUT(a,b) asm2C_OUT(a,b)
int8_t asm2C_IN(int16_t data);
#define IN(a,b) a = asm2C_IN(b);TESTJUMPTOBACKGROUND

#define STI // TODO: STI not implemented
#define PUSHF
#define POPF
#define NOP

#define CALL(label) \
if (setjmp(jmpbuffer) == 0) { \
    PUSH(?,jmpbuffer); \
    JMP(label); \
}

#define RET POP(x,jmpbuffer);longjmp(jmpbuffer, 0);

typedef struct __attribute__((packed)) Mem {
db dummy1[23];
dd liste_de_machin[11];
db trucs[16];
db beginningdata;
db dummy2;
db dummy3;
db dummy4;
dd taille_exe_gonfle;
db playsoundfx;
db buffer[65535];
db master;
db clavier[128];
db clavier_stuff;
db clavier_stuff2;
db clavier_extanded[128];
db pal_pic[16];
db dummy5[16];
db dummy6[16];
db dummy7[16];
db dummy8[16];
db dummy9[16];
db dummy10[16];
db dummy11[16];
db dummy12[16];
db dummy13[16];
db dummy14[16];
db dummy15[16];
db dummy16[16];
db dummy17[16];
db dummy18[16];
db dummy19[16];
db dummy20[16];
db dummy21[16];
db dummy22[16];
db dummy23[16];
db dummy24[16];
db dummy25[16];
db dummy26[16];
db dummy27[16];
db dummy28[16];
db dummy29[16];
db dummy30[16];
db dummy31[16];
db dummy32[16];
db dummy33[16];
db dummy34[16];
db dummy35[16];
db dummy36[16];
db dummy37[16];
db dummy38[16];
db dummy39[16];
db dummy40[16];
db dummy41[16];
db dummy42[16];
db dummy43[16];
db dummy44[16];
db dummy45[16];
db dummy46[16];
db dummy47[16];
db dummy48[16];
db dummy49[16];
db dummy50[16];
db dummy51[16];
db pal_pic2[16];
db dummy52[16];
db dummy53[16];
db dummy54[16];
db dummy55[16];
db dummy56[16];
db dummy57[16];
db dummy58[16];
db dummy59[16];
db dummy60[16];
db dummy61[16];
db dummy62[16];
db dummy63[16];
db dummy64[16];
db dummy65[16];
db dummy66[16];
db dummy67[16];
db dummy68[16];
db dummy69[16];
db dummy70[16];
db dummy71[16];
db dummy72[16];
db dummy73[16];
db dummy74[16];
db dummy75[16];
db dummy76[16];
db dummy77[16];
db dummy78[16];
db dummy79[16];
db dummy80[16];
db dummy81[16];
db dummy82[16];
db dummy83[16];
db dummy84[16];
db dummy85[16];
db dummy86[16];
db dummy87[16];
db dummy88[16];
db dummy89[16];
db dummy90[16];
db dummy91[16];
db dummy92[16];
db dummy93[16];
db dummy94[16];
db dummy95[16];
db dummy96[16];
db dummy97[16];
db dummy98[16];
db pal_jeu[16];
db dummy99[16];
db dummy100[16];
db dummy101[16];
db dummy102[16];
db dummy103[16];
db dummy104[16];
db dummy105[16];
db dummy106[16];
db dummy107[16];
db dummy108[16];
db dummy109[16];
db dummy110[16];
db dummy111[16];
db dummy112[16];
db dummy113[16];
db dummy114[16];
db dummy115[16];
db dummy116[16];
db dummy117[16];
db dummy118[16];
db dummy119[16];
db dummy120[16];
db dummy121[16];
db dummy122[16];
db dummy123[16];
db dummy124[16];
db dummy125[16];
db dummy126[16];
db dummy127[16];
db dummy128[16];
db dummy129[16];
db dummy130[16];
db dummy131[16];
db dummy132[16];
db dummy133[16];
db dummy134[16];
db dummy135[16];
db dummy136[16];
db dummy137[16];
db dummy138[16];
db dummy139[16];
db dummy140[16];
db dummy141[16];
db dummy142[16];
db dummy143[16];
db dummy144[16];
db dummy145[16];
db pal_med[16];
db dummy146[16];
db dummy147[16];
db dummy148[16];
db dummy149[16];
db dummy150[16];
db dummy151[16];
db dummy152[16];
db dummy153[16];
db dummy154[16];
db dummy155[16];
db dummy156[16];
db dummy157[16];
db dummy158[16];
db dummy159[16];
db dummy160[16];
db dummy161[16];
db dummy162[16];
db dummy163[16];
db dummy164[16];
db dummy165[16];
db dummy166[16];
db dummy167[16];
db dummy168[16];
db dummy169[16];
db dummy170[16];
db dummy171[16];
db dummy172[16];
db dummy173[16];
db dummy174[16];
db dummy175[16];
db dummy176[16];
db dummy177[16];
db dummy178[16];
db dummy179[16];
db dummy180[16];
db dummy181[16];
db dummy182[16];
db dummy183[16];
db dummy184[16];
db dummy185[16];
db dummy186[16];
db dummy187[16];
db dummy188[16];
db dummy189[16];
db dummy190[16];
db dummy191[16];
db dummy192[16];
db pal_vic[16];
db dummy193[16];
db dummy194[16];
db dummy195[16];
db dummy196[16];
db dummy197[16];
db dummy198[16];
db dummy199[16];
db dummy200[16];
db dummy201[16];
db dummy202[16];
db dummy203[16];
db dummy204[16];
db dummy205[16];
db dummy206[16];
db dummy207[16];
db dummy208[16];
db dummy209[16];
db dummy210[16];
db dummy211[16];
db dummy212[16];
db dummy213[16];
db dummy214[16];
db dummy215[16];
db dummy216[16];
db dummy217[16];
db dummy218[16];
db dummy219[16];
db dummy220[16];
db dummy221[16];
db dummy222[16];
db dummy223[16];
db dummy224[16];
db dummy225[16];
db dummy226[16];
db dummy227[16];
db dummy228[16];
db dummy229[16];
db dummy230[16];
db dummy231[16];
db dummy232[16];
db dummy233[16];
db dummy234[16];
db dummy235[16];
db dummy236[16];
db dummy237[16];
db dummy238[16];
db dummy239[16];
db pal_draw[16];
db dummy240[16];
db dummy241[16];
db dummy242[16];
db dummy243[16];
db dummy244[16];
db dummy245[16];
db dummy246[16];
db dummy247[16];
db dummy248[16];
db dummy249[16];
db dummy250[16];
db dummy251[16];
db dummy252[16];
db dummy253[16];
db dummy254[16];
db dummy255[16];
db dummy256[16];
db dummy257[16];
db dummy258[16];
db dummy259[16];
db dummy260[16];
db dummy261[16];
db dummy262[16];
db dummy263[16];
db dummy264[16];
db dummy265[16];
db dummy266[16];
db dummy267[16];
db dummy268[16];
db dummy269[16];
db dummy270[16];
db dummy271[16];
db dummy272[16];
db dummy273[16];
db dummy274[16];
db dummy275[16];
db dummy276[16];
db dummy277[16];
db dummy278[16];
db dummy279[16];
db dummy280[16];
db dummy281[16];
db dummy282[16];
db dummy283[16];
db dummy284[16];
db dummy285[16];
db dummy286[16];
dd winhdle;
dd vise_de_ca_haut[8];
dd vise_de_ca_haut2[8];
dd adder_inser_coin;
dd offset_ic[4];
dd viseur_ic2;
dd inser_coin;
dd stat_ou_pas;
dd acceleration;
dd attente_entre_chake_bombe;
dd nouvelle_attente_entre_chake_bombe2[19];
dd viseur__nouvelle_attente_entre_chake_bombe;
dd liste_bombbbb;
dw dummy287;
dw dummy288;
dd dummy289;
dd dummy290;
dw dummy291;
dw dummy292;
dd dummy293;
dd dummy294;
dw dummy295;
dw dummy296;
dd dummy297;
dd dummy298;
dw dummy299;
dw dummy300;
dd dummy301;
dd dummy302;
dw dummy303;
dw dummy304;
dd dummy305;
dd dummy306;
dw dummy307;
dw dummy308;
dd dummy309;
dd dummy310;
dw dummy311;
dw dummy312;
dd dummy313;
dd dummy314;
dw dummy315;
dw dummy316;
dd dummy317;
dd dummy318;
dw dummy319;
dw dummy320;
dd dummy321;
dd dummy322;
dw dummy323;
dw dummy324;
dd dummy325;
dd dummy326;
dw dummy327;
dw dummy328;
dd dummy329;
dd dummy330;
dw dummy331;
dw dummy332;
dd dummy333;
dd dummy334;
dw dummy335;
dw dummy336;
dd dummy337;
dd dummy338;
dw dummy339;
dw dummy340;
dd dummy341;
dd dummy342;
dw dummy343;
dw dummy344;
dd dummy345;
dd dummy346;
dw dummy347;
dw dummy348;
dd dummy349;
dd dummy350;
dw dummy351;
dw dummy352;
dd dummy353;
dd dummy354;
dw dummy355;
dw dummy356;
dd dummy357;
dd dummy358;
dw dummy359;
dw dummy360;
dd dummy361;
dd dummy362;
dw dummy363;
dw dummy364;
dd dummy365;
dd dummy366;
dw dummy367;
dw dummy368;
dd dummy369;
dd dummy370;
dw dummy371;
dw dummy372;
dd dummy373;
dd dummy374;
dw dummy375;
dw dummy376;
dd dummy377;
dd dummy378;
dw dummy379;
dw dummy380;
dd dummy381;
dd dummy382;
dw dummy383;
dw dummy384;
dd dummy385;
dd dummy386;
dw dummy387;
dw dummy388;
dd dummy389;
dd dummy390;
dw dummy391;
dw dummy392;
dd dummy393;
dd dummy394;
dw dummy395;
dw dummy396;
dd dummy397;
dd dummy398;
dw dummy399;
dw dummy400;
dd dummy401;
dd dummy402;
dw dummy403;
dw dummy404;
dd dummy405;
dd dummy406;
dw dummy407;
dw dummy408;
dd dummy409;
dd liste_bombbbb2;
dd special_nivo_6;
dd differentesply;
dd dummy410;
dd dummy411;
dd dummy412;
dd dummy413;
dd dummy414;
dd dummy415;
dd dummy416;
dd dummy417;
dd dummy418;
dd dummy419;
dd dummy420;
dd dummy421;
dd dummy422;
dd dummy423;
dd dummy424;
dd differentesply2;
dd temps_avant_demo;
dd touches_[8];
dd dummy425[8];
dd dummy426[8];
dd dummy427[8];
dd dummy428[8];
dd dummy429[8];
dd dummy430[8];
dd dummy431[8];
dd special_clignotement;
dd nuage_sympa[5];
dd dummy432[5];
dd dummy433[5];
dd dummy434[5];
dd dummy435[5];
dd dummy436[5];
dd dummy437[5];
dd dummy438[5];
dd dummy439[5];
dd dummy440[5];
dd dummy441[5];
dd dummy442[5];
dd dummy443[5];
dd dummy444[5];
dd dummy445[5];
dd dummy446[5];
dd arbre;
dd viseur_couleur;
dd last_voice;
dd monstro;
dd attente_nouveau_esc;
dd scrollyf;
dd tecte2;
dd packets_jeu_envoyes;
dd packets_jeu_recus;
dd kb_packets_jeu_envoyes;
dd adder_speciale_cfg_path;
dd windows;
dd offset_pause[10];
dd dummy447[4];
dd dummy448[10];
dd dummy449[17];
dd dummy450;
dd offset_si;
dd dummy451;
dd dummy452;
dd dummy453;
dd dummy454;
dd dummy455;
dd dummy456;
dd dummy457;
dd dummy458;
dd dummy459;
dd dummy460;
dd dummy461;
dd dummy462;
dd dummy463;
dd dummy464;
dd dummy465;
dd dummy466;
dd dummy467;
dd dummy468;
dd dummy469;
dd dummy470;
dd dummy471;
dd dummy472;
dd dummy473;
dd dummy474;
dd dummy475;
dd dummy476;
dd dummy477;
dd dummy478;
dd dummy479;
dd dummy480;
dd dummy481;
dd dummy482;
dd dummy483;
dd dummy484;
dd dummy485;
dd dummy486;
dd dummy487;
dd dummy488;
dd dummy489;
dd max_lost;
dd max_lost_master;
dd max_lost_master2;
dd new_lost;
db loaded_f[512];
dd nombre_de_dyna_x4;
dd changeiny[8];
dd dummy490[8];
dd viseur_change_in[8];
dd viseur_change_in_save[8];
dd anti_bomb[2];
dd dummy491[2];
dd dummy492[2];
dd dummy493[2];
dd machin2;
dd machin3;
dd machin[16];
dd dummy494[14];
dd dummy495;
dd dummy496[16];
dd dummy497[14];
dd dummy498;
dd rien_recu;
dd load_pcx_interne;
dd super_signe2;
dd duree_draw;
dd duree_med;
dd duree_vic;
dd affiche_raster;
dd save_banke;
dd kezax;
dd attente_avant_draw;
dd attente_avant_med;
dd load_handle;
dd pic_time;
dd adresse_des_fonds[4];
dd adresse_des_fonds_foot[2];
dd dummy499[2];
dd adresse_des_fonds_neige;
dd dummy500;
dd dummy501;
dd adresse_des_fonds_final[4];
dd adresse_des_fonds_foret[4];
dd adresse_des_fonds_nuage[4];
dd adresse_des_fonds_crayon[4];
dd adresse_des_fonds_soccer[4];
dd nombre_de_fond;
dd viseur_sur_fond;
dd adresse_des_draws[2];
dd nombre_de_draw;
dd viseur_sur_draw;
dd adresse_des_vic[4];
dd nombre_de_vic;
dd viseur_sur_vic;
dd attente;
dd kelle_donnee[5];
dd dummy502[3];
dd kelle_fin[5];
dd dummy503[3];
dd kelle_truc[5];
dd dummy504[3];
dd kelle_bonus[5];
dd dummy505[3];
dd kelle_apocalypse[5];
dd dummy506[3];
dd kelle_duree[5];
dd dummy507[3];
dw offset_briques[5];
dw dummy508[3];
dd kelle_offset_fond[5];
dd dummy509[3];
dw kel_viseur_brike_fin[5];
dw dummy510[3];
dw lapin_mort[4];
dw dummy511[4];
dw dummy512[4];
dw dummy513[4];
dw lapin_mortg[4];
dw dummy514[4];
dw dummy515[4];
dw dummy516[4];
dw lapin2[4];
dw dummy517[4];
dw dummy518[4];
dw dummy519[4];
dw dummy520[4];
dw dummy521[4];
dw dummy522;
dw lapin2g[4];
dw dummy523[4];
dw dummy524[4];
dw dummy525[4];
dw dummy526[4];
dw dummy527[4];
dw dummy528;
dw lapin2___[4];
dw dummy529[4];
dw dummy530[4];
dw dummy531[4];
dw lapin2___g[4];
dw dummy532[4];
dw dummy533[4];
dw dummy534[4];
dw lapin2_[4];
dw dummy535[4];
dw dummy536[4];
dw dummy537[4];
dw lapin2_g[4];
dw dummy538[4];
dw dummy539[4];
dw dummy540[4];
dw lapin2__[4];
dw dummy541[4];
dw dummy542[4];
dw dummy543[4];
dw lapin2__g[4];
dw dummy544[4];
dw dummy545[4];
dw dummy546[4];
dw grosbleu[4];
dw dummy547[4];
dw dummy548[4];
dw dummy549[4];
dw dummy550[4];
dw dummy551[4];
dw dummy552;
dw coca[4];
dw dummy553[4];
dw dummy554[4];
dw dummy555[4];
dw dummy556[8];
dw dummy557;
dw escargot[4];
dw dummy558[4];
dw dummy559[4];
dw dummy560[4];
dw dummy561[4];
dw dummy562[4];
dw dummy563;
dw old_school[4];
dw dummy564[4];
dw dummy565[4];
dw dummy566[4];
dw dummy567[3];
dw dummy568[5];
dw dummy569;
dw bleu_triste[4];
dw dummy570[4];
dw dummy571[4];
dw dummy572[4];
dw dummy573[4];
dw dummy574[4];
dw dummy575;
dw machine[16];
dw dummy576[4];
dw dummy577[4];
dw dummy578;
dw petit_jaune[4];
dw dummy579[4];
dw dummy580[4];
dw dummy581[4];
dw dummy582[8];
dw dummy583;
dw blanc[4];
dw dummy584[4];
dw dummy585[4];
dw dummy586[4];
dw dummy587[4];
dw dummy588[4];
dw dummy589;
dw bleu[4];
dw dummy590[4];
dw dummy591[4];
dw dummy592[4];
dw dummy593[6];
dw dummy594[2];
dw dummy595;
dw rouge[4];
dw dummy596[4];
dw dummy597[4];
dw dummy598[4];
dw dummy599[8];
dw dummy600;
dw vert[4];
dw dummy601[4];
dw dummy602[4];
dw dummy603[4];
dw dummy604[8];
dw dummy605;
dw blancg[4];
dw dummy606[4];
dw dummy607[4];
dw dummy608[4];
dw dummy609[8];
dw dummy610;
dw bleug[4];
dw dummy611[4];
dw dummy612[4];
dw dummy613[4];
dw dummy614[4];
dw dummy615[2];
dw dummy616[2];
dw dummy617;
dw rougeg[4];
dw dummy618[4];
dw dummy619[4];
dw dummy620[4];
dw dummy621[8];
dw dummy622;
dw vertg[4];
dw dummy623[4];
dw dummy624[4];
dw dummy625[4];
dw dummy626[4];
dw dummy627[4];
dw dummy628;
dd compteur_nuage;
dd changementzz;
dd changementzz2;
dd changement;
db truc[416];
db truc2[416];
db truc_x[416];
db truc_y[416];
db truc_monstre[416];
dw central_b[7];
dw dummy629[7];
dw dummy630[7];
dw dummy631[7];
dw dummy632[7];
dw dummy633[7];
dw dummy634[7];
dd touches[8];
dd avance[8];
dd avance2[8];
dd touches_save[8];
db action[32];
dd vie[8];
dd victoires[8];
dd latest_victory;
dd team[8];
dd nombre_minimum_de_dyna;
dd n_team[8];
dd dummy635;
dd c_team[8];
dd dummy636;
dd s_team[8];
dd dummy637;
dd viseur_victory[2];
dd dummy638[2];
dd dummy639[2];
dd dummy640[2];
dd viseur_victoryc[2];
dd dummy641[2];
dd dummy642[2];
dd dummy643[2];
dd viseur_victoryg[8];
dd viseur_name[2];
dd dummy644[2];
dd dummy645[2];
dd dummy646[2];
dd viseur_namec[2];
dd dummy647[2];
dd dummy648[2];
dd dummy649[2];
dd viseur_nameg[2];
dd dummy650[2];
dd dummy651[2];
dd dummy652[2];
dw offset_medaille[13];
dw dummy653[3];
dd infos_j_n[5];
dd infos_m_n[40];
dd random_place[8];
dd dummy654[8];
dd dummy655[8];
dd dummy656[8];
dd dummy657[8];
dd dummy658[8];
dd dummy659[8];
dd dummy660[8];
dd dummy661[8];
dd dummy662[8];
dd dummy663[8];
dd dummy664[8];
dd dummy665[8];
dd dummy666[8];
dd dummy667[8];
dd dummy668[8];
dd last_bomb[8];
dd infojoueur[8];
dd infojoueur2[5];
dd j1[5];
dd j2[5];
dd j3[5];
dd j4[5];
dd j5[5];
dd j6[5];
dd j7[5];
dd j8[5];
dd liste_bombe;
dd dummy669[1482];
dw donnee[8];
dw dummy670[8];
dw dummy671[8];
dd ooo546[8];
dw dummy672[8];
dw dummy673[8];
dd dummy674[8];
dd liste_couleur[8];
dd nombre_de_coups[8];
dd clignotement[8];
dd pousseur[8];
dd patineur[8];
dd vitesse_monstre[8];
dd tribombe2[8];
dd tribombe[8];
dd invinsible[8];
dd blocage[8];
dd lapipipino[8];
dd lapipipino2[8];
dd lapipipino3[8];
dd lapipipino4[8];
dd lapipipino5[8];
dd lapipipino6[8];
dd lapipipino7[8];
db donnee4[72];
dd viseur_liste_terrain;
dd nombre_de_dyna;
db action_replay;
dd nombre_de_monstres;
dd nombre_de_vbl_avant_le_droit_de_poser_bombe;
db ordre2;
db speed_raster;
db detail;
db mechant;
db terrain;
db team3;
db pauseur2;
dw temps;
db bdraw666[2];
dw adder_bdraw;
dw blow_what2[14];
dw blow_what[14];
dd kel_ombre;
dw ombres[8];
dw briques[495];
dw bombes[495];
db buffer_vide[1500];
dd max_packet;
dd liste_couleur_malade[2];
dd dummy675[2];
dd dummy676[2];
dd dummy677[2];
dd control_joueur[8];
dd control_joueur2[8];
dd name_joueur[8];
dd temps_joueur[8];
db liste_adresse[160];
dd nb_ordy_connected;
dd last_packet_size;
db adresse_master[12];
dd last_name;
db total_play[6];
db dummy678[6];
db dummy679[6];
db dummy680[6];
db dummy681[6];
db dummy682[6];
db dummy683[6];
db dummy684[6];
db dummy685[3];
db dummy686[13];
db total_t[6];
db dummy687[6];
db dummy688[6];
db dummy689[6];
db dummy690[6];
db dummy691[6];
db dummy692[6];
db dummy693[6];
db dummy694[2];
db dummy695[14];
db dummy696[6];
db dummy697[6];
db dummy698[6];
db dummy699[6];
db dummy700[6];
db dummy701[6];
db dummy702[6];
db dummy703[6];
db dummy704[2];
db dummy705[14];
db dummy706[6];
db dummy707[6];
db dummy708[6];
db dummy709[6];
db dummy710[6];
db dummy711[6];
db dummy712[6];
db dummy713[6];
db dummy714[2];
db dummy715[14];
db dummy716[6];
db dummy717[6];
db dummy718[6];
db dummy719[6];
db dummy720[6];
db dummy721[6];
db dummy722[6];
db dummy723[6];
db dummy724[2];
db dummy725[14];
db dummy726[6];
db dummy727[6];
db dummy728[6];
db dummy729[6];
db dummy730[6];
db dummy731[6];
db dummy732[6];
db dummy733[6];
db dummy734[2];
db dummy735[14];
db dummy736[6];
db dummy737[6];
db dummy738[6];
db dummy739[6];
db dummy740[6];
db dummy741[6];
db dummy742[6];
db dummy743[6];
db dummy744[2];
db dummy745[14];
db dummy746[6];
db dummy747[6];
db dummy748[6];
db dummy749[6];
db dummy750[6];
db dummy751[6];
db dummy752[6];
db dummy753[6];
db dummy754[2];
db dummy755[14];
db dummy756[6];
db dummy757[6];
db dummy758[6];
db dummy759[6];
db dummy760[6];
db dummy761[6];
db dummy762[6];
db dummy763[6];
db dummy764[2];
db dummy765[14];
db donnee2[7];
db dummy766[7];
db dummy767[7];
db dummy768[7];
db dummy769[7];
db dummy770[7];
db dummy771[7];
db dummy772[7];
db dummy773[2];
db dummy774;
db donnee98[82];
db menu_[4];
db game_[4];
db demo_[4];
db warning_ipx[45];
db warning_ipx2[39];
db warning_ipx3[39];
db no_dyna[45];
db no_dyna2[83];
db pas_de_mem[70];
db pbs1[43];
db pbs2[56];
db socketipx[22];
db erreur_dans_ecoute2[21];
db information[53];
db pasipx[58];
db msg1[18];
db msg2[16];
db msg3[47];
db msg4[5];
db nomdetriche[4];
db nomdetriche2[4];
db ipx[65];
db loaderror[78];
db busy[22];
db busy2[79];
db version2[42];
db version2b[25];
db erreur3[51];
db ohohohohoh[57];
db kill[12];
db tected[25];
db tecte[102];
db dummy775[462];
db message1[6];
db dummy776[6];
db dummy777[6];
db dummy778[14];
db dummy779[6];
db dummy780[6];
db dummy781[6];
db dummy782[14];
db dummy783[6];
db dummy784[6];
db dummy785[6];
db dummy786[14];
db dummy787[6];
db dummy788[6];
db dummy789[6];
db dummy790[14];
db message2[6];
db dummy791[6];
db dummy792[6];
db dummy793[14];
db dummy794[6];
db dummy795[6];
db dummy796[6];
db dummy797[14];
db dummy798[6];
db dummy799[6];
db dummy800[6];
db dummy801[14];
db dummy802[6];
db dummy803[6];
db dummy804[6];
db dummy805[14];
db message3[6];
db dummy806[6];
db dummy807[6];
db dummy808[14];
db dummy809[6];
db dummy810[6];
db dummy811[6];
db dummy812[14];
db dummy813[6];
db dummy814[6];
db dummy815[6];
db dummy816[14];
db dummy817[6];
db dummy818[6];
db dummy819[6];
db dummy820[14];
db mess_kli[6];
db dummy821[6];
db dummy822[6];
db dummy823[14];
db dummy824[6];
db dummy825[6];
db dummy826[6];
db dummy827[14];
db dummy828[6];
db dummy829[6];
db dummy830[6];
db dummy831[14];
db dummy832[6];
db dummy833[6];
db dummy834[6];
db dummy835[14];
db mess_luc[6];
db dummy836[6];
db dummy837[6];
db dummy838[14];
db dummy839[6];
db dummy840[6];
db dummy841[6];
db dummy842[14];
db dummy843[6];
db dummy844[6];
db dummy845[6];
db dummy846[14];
db dummy847[6];
db dummy848[6];
db dummy849[6];
db dummy850[14];
db mess_frd[6];
db dummy851[6];
db dummy852[6];
db dummy853[14];
db dummy854[6];
db dummy855[6];
db dummy856[6];
db dummy857[14];
db dummy858[6];
db dummy859[6];
db dummy860[6];
db dummy861[14];
db dummy862[6];
db dummy863[6];
db dummy864[6];
db dummy865[14];
db mess_jag[6];
db dummy866[6];
db dummy867[6];
db dummy868[14];
db dummy869[6];
db dummy870[6];
db dummy871[6];
db dummy872[14];
db dummy873[6];
db dummy874[6];
db dummy875[6];
db dummy876[14];
db dummy877[6];
db dummy878[6];
db dummy879[6];
db dummy880[14];
db mess_din[6];
db dummy881[6];
db dummy882[6];
db dummy883[14];
db dummy884[6];
db dummy885[6];
db dummy886[6];
db dummy887[14];
db dummy888[6];
db dummy889[6];
db dummy890[6];
db dummy891[14];
db dummy892[6];
db dummy893[6];
db dummy894[6];
db dummy895[14];
db mess_jdg[6];
db dummy896[6];
db dummy897[6];
db dummy898[14];
db dummy899[6];
db dummy900[6];
db dummy901[6];
db dummy902[14];
db mess_rmd[6];
db dummy903[6];
db dummy904[6];
db dummy905[14];
db dummy906[6];
db dummy907[6];
db dummy908[6];
db dummy909[14];
db dummy910[6];
db dummy911[6];
db dummy912[6];
db dummy913[14];
db dummy914[6];
db dummy915[6];
db dummy916[6];
db dummy917[14];
db mess_kor[6];
db dummy918[6];
db dummy919[6];
db dummy920[14];
db dummy921[6];
db dummy922[6];
db dummy923[6];
db dummy924[14];
db dummy925[6];
db dummy926[6];
db dummy927[6];
db dummy928[14];
db dummy929[6];
db dummy930[6];
db dummy931[6];
db dummy932[14];
db mess_sl1[6];
db dummy933[6];
db dummy934[6];
db dummy935[14];
db dummy936[6];
db dummy937[6];
db dummy938[6];
db dummy939[14];
db dummy940[6];
db dummy941[6];
db dummy942[6];
db dummy943[14];
db dummy944[6];
db dummy945[6];
db dummy946[6];
db dummy947[14];
db mess_adr[6];
db dummy948[6];
db dummy949[6];
db dummy950[14];
db dummy951[6];
db dummy952[6];
db dummy953[6];
db dummy954[14];
db dummy955[6];
db dummy956[6];
db dummy957[6];
db dummy958[14];
db dummy959[6];
db dummy960[6];
db dummy961[6];
db dummy962[14];
db mess_wil[6];
db dummy963[6];
db dummy964[6];
db dummy965[14];
db dummy966[6];
db dummy967[6];
db dummy968[6];
db dummy969[14];
db mess_exo[6];
db dummy970[6];
db dummy971[6];
db dummy972[14];
db dummy973[6];
db dummy974[6];
db dummy975[6];
db dummy976[14];
db mess_cl[6];
db dummy977[6];
db dummy978[6];
db dummy979[14];
db dummy980[6];
db dummy981[6];
db dummy982[6];
db dummy983[14];
db mess_ben[6];
db dummy984[6];
db dummy985[6];
db dummy986[14];
db dummy987[6];
db dummy988[6];
db dummy989[6];
db dummy990[14];
db mess_aaa[6];
db dummy991[6];
db dummy992[6];
db dummy993[14];
db dummy994[6];
db dummy995[6];
db dummy996[6];
db dummy997[14];
db mess_fzf[6];
db dummy998[6];
db dummy999[6];
db dummy1000[14];
db dummy1001[6];
db dummy1002[6];
db dummy1003[6];
db dummy1004[14];
db dummy1005[6];
db dummy1006[6];
db dummy1007[6];
db dummy1008[14];
db dummy1009[6];
db dummy1010[6];
db dummy1011[6];
db dummy1012[14];
db mess_het[6];
db dummy1013[6];
db dummy1014[6];
db dummy1015[14];
db dummy1016[6];
db dummy1017[6];
db dummy1018[6];
db dummy1019[14];
db dummy1020[6];
db dummy1021[6];
db dummy1022[6];
db dummy1023[14];
db dummy1024[6];
db dummy1025[6];
db dummy1026[6];
db dummy1027[14];
db mess_big[6];
db dummy1028[6];
db dummy1029[6];
db dummy1030[14];
db dummy1031[6];
db dummy1032[6];
db dummy1033[6];
db dummy1034[14];
db dummy1035[6];
db dummy1036[6];
db dummy1037[6];
db dummy1038[14];
db dummy1039[6];
db dummy1040[6];
db dummy1041[6];
db dummy1042[14];
db mess_hak[6];
db dummy1043[6];
db dummy1044[6];
db dummy1045[14];
db dummy1046[6];
db dummy1047[6];
db dummy1048[6];
db dummy1049[14];
db dummy1050[6];
db dummy1051[6];
db dummy1052[6];
db dummy1053[14];
db dummy1054[6];
db dummy1055[6];
db dummy1056[6];
db dummy1057[14];
db mess_jc[6];
db dummy1058[6];
db dummy1059[6];
db dummy1060[14];
db dummy1061[6];
db dummy1062[6];
db dummy1063[6];
db dummy1064[14];
db defo[4];
db intro_txt[78];
db dummy1065[80];
db dummy1066[80];
db dummy1067[79];
db dummy1068[80];
db dummy1069[4];
db nick_t[7];
db dummy1070[7];
db dummy1071[7];
db dummy1072[7];
db dummy1073[7];
db dummy1074[7];
db dummy1075[7];
db dummy1076[7];
db dummy1077[8];
db dummy1078[7];
db dummy1079[7];
db dummy1080[7];
db dummy1081[7];
db dummy1082[7];
db dummy1083[7];
db dummy1084[7];
db dummy1085[7];
db dummy1086[8];
db dummy1087[7];
db dummy1088[7];
db dummy1089[7];
db dummy1090[7];
db dummy1091[7];
db dummy1092[7];
db dummy1093[7];
db dummy1094[7];
db dummy1095[8];
db dummy1096[7];
db dummy1097[7];
db dummy1098[7];
db dummy1099[7];
db dummy1100[7];
db dummy1101[7];
db dummy1102[7];
db dummy1103[7];
db dummy1104[8];
db dummy1105[7];
db dummy1106[7];
db dummy1107[7];
db dummy1108[7];
db dummy1109[7];
db dummy1110[7];
db dummy1111[7];
db dummy1112[7];
db dummy1113[8];
db dummy1114[7];
db dummy1115[7];
db dummy1116[7];
db dummy1117[7];
db dummy1118[7];
db dummy1119[7];
db dummy1120[7];
db dummy1121[7];
db dummy1122[8];
db dummy1123[7];
db dummy1124[7];
db dummy1125[7];
db dummy1126[7];
db dummy1127[7];
db dummy1128[7];
db dummy1129[7];
db dummy1130[7];
db dummy1131[8];
db dummy1132[7];
db dummy1133[7];
db dummy1134[7];
db dummy1135[7];
db dummy1136[7];
db dummy1137[7];
db dummy1138[7];
db dummy1139[7];
db dummy1140[8];
db dummy1141[6];
db love_si[4];
db dummy1142[4];
db dummy1143[4];
db dummy1144[4];
db dummy1145[4];
db dummy1146[4];
db dummy1147[4];
db dummy1148[4];
db dummy1149[4];
db dummy1150[4];
db dummy1151[4];
db dummy1152[4];
db dummy1153[4];
db dummy1154[4];
db dummy1155[4];
db dummy1156[4];
db dummy1157[4];
db dummy1158[4];
db dummy1159[4];
db dummy1160[4];
db dummy1161[4];
db rmd_file_name[2];
db iff_file_name[13];
db winsux[18];
db pas_ligne[18];
db info666[44];
db dummy1162[37];
db dummy1163[58];
db dummy1164[52];
db dummy1165[47];
db dummy1166[55];
db dummy1167[43];
db dummy1168[45];
db dummy1169[38];
db dummy1170[67];
db dummy1171[55];
db dummy1172[55];
db dummy1173[56];
db dummy1174[40];
db dummy1175[81];
db dummy1176[30];
db dummy1177[43];
db dummy1178[31];
db dummy1179[51];
db dummy1180[22];
db pathing[67];
db setup_[25];
db setup_k[53];
db setup_e[45];
db setup_m[36];
db setup_w[53];
db setup_d[35];
db setup_3[46];
db setup_t[31];
db setup_f[32];
db setup_b[54];
db setup_2[57];
db setup_n[42];
db setup_x[48];
db setup_c[43];
db setup_s[50];
db setup_l[65];
db setup_n_error[60];
db test1[30];
db nom_terrain[8];
db dummy1181[8];
db dummy1182[8];
db dummy1183[8];
db dummy1184[8];
db dummy1185[8];
db dummy1186[8];
db dummy1187[8];
db cfgfile[14];
db cfgfile2;
db reccord[13];
db reccord3[9];
db reccord2[13];
db suite[4];
db suite2[24];
db suite3[73];
db cfgerror[79];
db errorcfg[29];
db message_mem_rp[53];
db okcfg[37];
db okcfg3[36];
db win[55];
db nowin[39];
db terminalor[78];
db dummy1188[49];
db nulosproduction[60];
db stat1[10];
db stat2[7];
db stat3[9];
db gameover[38];
db no_server_[33];
db select_server_[42];
db cnx1[32];
db transformateur_98[13];
db cnx2[6];
db notreadresse[4];
db dummy1189[6];
dw dummy1190;
db toutes_adresse[4];
db dummy1191[6];
dw dummy1192;
dd ecb1;
dd dummy1193;
db dummy1194;
db dummy1195;
dw dummy1196;
db dummy1197[16];
db dummy1198[6];
dw dummy1199;
dd dummy1200;
dw dummy1201;
dd dummy1202;
dw dummy1203;
dw header_ecoute;
dw dummy1204;
db dummy1205;
db dummy1206;
db dummy1207[4];
db dummy1208[6];
dw dummy1209;
db dummy1210[4];
db dummy1211[6];
dw dummy1212;
dd ecb3;
dd dummy1213;
db dummy1214;
db dummy1215;
dw dummy1216;
db dummy1217[16];
db dummy1218[6];
dw dummy1219;
dd dummy1220;
dw dummy1221;
dd dummy1222;
dw dummy1223;
dw header_ecoute3;
dw dummy1224;
db dummy1225;
db dummy1226;
db dummy1227[4];
db dummy1228[6];
dw dummy1229;
db dummy1230[4];
db dummy1231[6];
dw dummy1232;
db recu_data[1500];
db recu_data3;
db dummy1233;
db packed_data[1500];
db donnee3;
db envoye_data[1500];
dd call_int;
dd dummy1234;
dd dummy1235;
dd dummy1236;
dd dummy1237;
dd dummy1238;
dd dummy1239;
dd dummy1240;
dw dummy1241;
dw dummy1242;
dw dummy1243;
dw dummy1244;
dw dummy1245;
dw dummy1246;
dw dummy1247;
dw dummy1248;
dw dummy1249;
dd differents_offset_possible[4];
dd dummy1250[4];
dd dummy1251[4];
dd dummy1252[4];
dd dummy1253[4];
dd dummy1254[4];
dd dummy1255[4];
dd dummy1256[4];
dd dummy1257[4];
dd dummy1258[4];
dd dummy1259[4];
dd dummy1260[4];
dd dummy1261[4];
dd dummy1262[4];
dd dummy1263[4];
dd dummy1264[4];
dd dummy1265;
dd packed_liste[12];
dd dummy1266[24];
dd dummy1267[22];
dd dummy1268;
dd total_liste;
dd iff_liste[13];
dd dummy1269;
dd lapin_mania[2];
dd dummy1270[2];
dd dummy1271[2];
dd dummy1272[2];
dd lapin_mania_malade[2];
dd dummy1273[2];
dd dummy1274[2];
dd dummy1275[2];
dd lapin_mania1[2];
dd dummy1276[2];
dd dummy1277[2];
dd dummy1278[2];
dd lapin_mania2[2];
dd dummy1279[2];
dd dummy1280[2];
dd dummy1281[2];
dd lapin_mania3[2];
dd dummy1282[2];
dd dummy1283[2];
dd dummy1284[2];
dd lapin_mania4[2];
dd dummy1285[2];
dd dummy1286[2];
dd dummy1287[2];
dd lapin_mania5[2];
dd dummy1288[2];
dd dummy1289[2];
dd dummy1290[2];
dw donnee_s[8];
dw dummy1291[8];
dw dummy1292[8];
dd ooo34[8];
dw dummy1293[8];
dw dummy1294[8];
dd dummy1295[8];
dd dummy1296[8];
dd dummy1297[8];
dd dummy1298[5];
dd dummy1299[40];
dd dummy1300[8];
dd dummy1301[8];
dd dummy1302[2];
dd dummy1303[8];
dd dummy1304[8];
dd dummy1305;
dd dummy1306;
db dummy1307[8];
db dummy1308[8];
db dummy1309[8];
db dummy1310[8];
dw donnee_foot[8];
dw dummy1311[8];
dw dummy1312[8];
dd dummy1313[8];
dw dummy1314[8];
dw dummy1315[8];
dd dummy1316[8];
dd dummy1317[8];
dd dummy1318[8];
dd dummy1319[5];
dd dummy1320[40];
dd dummy1321[8];
dd dummy1322[8];
dd dummy1323[2];
dd dummy1324[8];
dd dummy1325[8];
dd dummy1326;
dd dummy1327;
db dummy1328[8];
db dummy1329[8];
db dummy1330[8];
db dummy1331[8];
dw donnee_soccer[8];
dw dummy1332[8];
dw dummy1333[8];
dd dummy1334[8];
dw dummy1335[8];
dw dummy1336[8];
dd dummy1337[8];
dd dummy1338[8];
dd dummy1339[8];
dd dummy1340[5];
dd dummy1341[10];
dd dummy1342[30];
dd dummy1343[8];
dd dummy1344[8];
dd dummy1345[2];
dd dummy1346[8];
dd dummy1347[8];
dd dummy1348;
dd dummy1349;
db dummy1350[8];
db dummy1351[8];
db dummy1352[8];
db dummy1353[8];
dw donnee_h[8];
dw dummy1354[8];
dw dummy1355[8];
dd dummy1356[8];
dw dummy1357[8];
dw dummy1358[8];
dd dummy1359[8];
dd dummy1360[8];
dd dummy1361[8];
dd dummy1362[5];
dd dummy1363[40];
dd dummy1364[8];
dd dummy1365[8];
dd dummy1366[2];
dd dummy1367[8];
dd dummy1368[8];
dd dummy1369;
dd dummy1370;
db dummy1371[8];
db dummy1372[8];
db dummy1373[8];
db dummy1374[8];
dw donnee_n[8];
dw dummy1375[8];
dw dummy1376[8];
dd dummy1377[8];
dw dummy1378[8];
dw dummy1379[8];
dd dummy1380[8];
dd dummy1381[8];
dd dummy1382[8];
dd dummy1383[5];
dd dummy1384[10];
dd dummy1385[5];
dd dummy1386[5];
dd dummy1387[5];
dd dummy1388[5];
dd dummy1389[5];
dd dummy1390[5];
dd dummy1391[8];
dd dummy1392[8];
dd dummy1393[2];
dd dummy1394[8];
dd dummy1395[8];
dd dummy1396;
dd dummy1397;
db dummy1398[8];
db dummy1399[8];
db dummy1400[8];
db dummy1401[8];
dw donnee_c[8];
dw dummy1402[8];
dw dummy1403[8];
dd dummy1404[8];
dw dummy1405[8];
dw dummy1406[8];
dd dummy1407[8];
dd dummy1408[8];
dd dummy1409[8];
dd dummy1410[5];
dd dummy1411[40];
dd dummy1412[8];
dd dummy1413[8];
dd dummy1414[2];
dd dummy1415[8];
dd dummy1416[8];
dd dummy1417;
dd dummy1418;
db dummy1419[8];
db dummy1420[8];
db dummy1421[8];
db dummy1422[8];
dw donnee_f[8];
dw dummy1423[8];
dw dummy1424[8];
dd dummy1425[8];
dw dummy1426[8];
dw dummy1427[8];
dd dummy1428[8];
dd dummy1429[8];
dd dummy1430[8];
dd dummy1431[5];
dd dummy1432[40];
dd dummy1433[8];
dd dummy1434[8];
dd dummy1435[2];
dd dummy1436[8];
dd dummy1437[8];
dd dummy1438;
dd dummy1439;
db dummy1440[8];
db dummy1441[8];
db dummy1442[8];
db dummy1443[8];
dw donnee_s_neige[8];
dw dummy1444[8];
dw dummy1445[8];
dd dummy1446[8];
dw dummy1447[8];
dw dummy1448[8];
dd dummy1449[8];
dd dummy1450[8];
dd dummy1451[8];
dd dummy1452[5];
dd dummy1453[40];
dd dummy1454[8];
dd dummy1455[8];
dd dummy1456[2];
dd dummy1457[8];
dd dummy1458[8];
dd dummy1459;
dd dummy1460;
db dummy1461[8];
db dummy1462[8];
db dummy1463[8];
db dummy1464[8];
dd liste_couleur_normal[2];
dd dummy1465[2];
dd dummy1466[2];
dd dummy1467[2];
dd s_normal[8];
dw l_normal[8];
dw c_normal[8];
dd a_normal[8];
dd r_normal[8];
db truc_fin[416];
dd dummy1468;
db truc_fin_s[32];
db dummy1469[32];
db dummy1470[32];
db dummy1471[32];
db dummy1472[32];
db dummy1473[32];
db dummy1474[32];
db dummy1475[32];
db dummy1476[32];
db dummy1477[32];
db dummy1478[32];
db dummy1479[32];
db dummy1480[32];
dd dummy1481;
db truc_fin_soccer[32];
db dummy1482[32];
db dummy1483[32];
db dummy1484[32];
db dummy1485[32];
db dummy1486[32];
db dummy1487[32];
db dummy1488[32];
db dummy1489[32];
db dummy1490[32];
db dummy1491[32];
db dummy1492[32];
db dummy1493[32];
dd dummy1494;
db truc_fin_s_c[32];
db dummy1495[32];
db dummy1496[32];
db dummy1497[32];
db dummy1498[32];
db dummy1499[32];
db dummy1500[32];
db dummy1501[32];
db dummy1502[32];
db dummy1503[32];
db dummy1504[32];
db dummy1505[32];
db dummy1506[32];
dd dummy1507;
db truc_fin_s_m[32];
db dummy1508[32];
db dummy1509[32];
db dummy1510[32];
db dummy1511[32];
db dummy1512[32];
db dummy1513[32];
db dummy1514[32];
db dummy1515[32];
db dummy1516[32];
db dummy1517[32];
db dummy1518[32];
db dummy1519[32];
dd dummy1520;
db truc_fin_s_n[32];
db dummy1521[32];
db dummy1522[32];
db dummy1523[32];
db dummy1524[32];
db dummy1525[32];
db dummy1526[32];
db dummy1527[32];
db dummy1528[32];
db dummy1529[32];
db dummy1530[32];
db dummy1531[32];
db dummy1532[32];
dd dummy1533;
db truc_s[32];
db dummy1534[32];
db dummy1535[32];
db dummy1536[32];
db dummy1537[32];
db dummy1538[32];
db dummy1539[32];
db dummy1540[32];
db dummy1541[32];
db dummy1542[32];
db dummy1543[32];
db dummy1544[32];
db dummy1545[32];
db truc_foot[32];
db dummy1546[32];
db dummy1547[32];
db dummy1548[32];
db dummy1549[32];
db dummy1550[32];
db dummy1551[32];
db dummy1552[32];
db dummy1553[32];
db dummy1554[32];
db dummy1555[32];
db dummy1556[32];
db dummy1557[32];
db truc_soccer[32];
db dummy1558[32];
db dummy1559[32];
db dummy1560[32];
db dummy1561[32];
db dummy1562[32];
db dummy1563[32];
db dummy1564[32];
db dummy1565[32];
db dummy1566[32];
db dummy1567[32];
db dummy1568[32];
db dummy1569[32];
db truc_n[32];
db dummy1570[32];
db dummy1571[32];
db dummy1572[32];
db dummy1573[32];
db dummy1574[32];
db dummy1575[32];
db dummy1576[32];
db dummy1577[32];
db dummy1578[32];
db dummy1579[32];
db dummy1580[32];
db dummy1581[32];
db truc_c[32];
db dummy1582[32];
db dummy1583[32];
db dummy1584[32];
db dummy1585[32];
db dummy1586[32];
db dummy1587[32];
db dummy1588[32];
db dummy1589[32];
db dummy1590[32];
db dummy1591[32];
db dummy1592[32];
db dummy1593[32];
db truc_h[32];
db dummy1594[32];
db dummy1595[32];
db dummy1596[32];
db dummy1597[32];
db dummy1598[32];
db dummy1599[32];
db dummy1600[32];
db dummy1601[32];
db dummy1602[32];
db dummy1603[32];
db dummy1604[32];
db dummy1605[32];
db truc_f[32];
db dummy1606[32];
db dummy1607[32];
db dummy1608[32];
db dummy1609[32];
db dummy1610[32];
db dummy1611[32];
db dummy1612[32];
db dummy1613[32];
db dummy1614[32];
db dummy1615[32];
db dummy1616[32];
db dummy1617[32];
db truc_neige[32];
db dummy1618[32];
db dummy1619[32];
db dummy1620[32];
db dummy1621[32];
db dummy1622[32];
db dummy1623[32];
db dummy1624[32];
db dummy1625[32];
db dummy1626[32];
db dummy1627[32];
db dummy1628[32];
db dummy1629[32];
db truc2_save_foot[32];
db dummy1630[32];
db truc2_save[13];
db truc2_save_n[32];
db dummy1631[32];
db dummy1632[32];
db dummy1633[32];
db dummy1634[32];
db dummy1635[32];
db dummy1636[32];
db dummy1637[32];
db dummy1638[32];
db dummy1639[32];
db dummy1640[32];
db dummy1641[32];
db dummy1642[32];
dd ia[16];
db ordre;
db dummy1643[4];
dw fx[14];
db texte1[1024];
db panning2[19];
dd maladie[8];
dd offset_oiseau[16];
dd dummy1644[16];
dw lost_msg;
dw grosse_sochette;
dw mort_de_lapin[6];
dw dummy1645[6];
dw dummy1646[6];
dw dummy1647[6];
dw dummy1648[6];
dw dummy1649[2];
dw saut_de_lapin2[6];
dw dummy1650[6];
dw dummy1651[5];
dw dummy1652[3];
dw dummy1653[6];
dw dummy1654[6];
dw dummy1655;
dw dummy1656[4];
dw dummy1657[4];
dw saut_de_lapin[6];
dw dummy1658[6];
dw dummy1659[5];
dw dummy1660[3];
dw dummy1661[6];
dw dummy1662[6];
dw dummy1663;
dw dummy1664[4];
dw dummy1665[4];
dw dummy1666[4];
dw dummy1667[4];
dw dummy1668[4];
dw dummy1669[4];
db save64;
db windowsnetwork;
db economode;
db demande_partie_slave;
db demande_partie_slave2;
db kli_option;
db balance_le_bdrawn;
db bdraw1;
db on_a_bien_fait_une_partie;
db on_les_dans_le_menu;
db sortie_slave;
db modeinfo;
db willrecord;
db nomonster;
db twice;
db twice2;
dw offset_fille[16];
db offset_supporter[4];
db offset_cameraman[4];
db dummy1670[12];
db dummy1671[4];
db dummy1672[12];
db dummy1673[8];
db dummy1674[8];
db dummy1675[8];
db dummy1676[4];
db dummy1677[12];
db dummy1678[8];
db dummy1679[4];
db dummy1680[12];
db pic_de_tout_debut;
db une_touche_a_telle_ete_pressee;
db sors_du_menu_aussitot;
db team3_sauve;
db special_on_a_loadee_nivo;
db record_user;
db previentlmesenfants;
db couleurssss[64];
db dummy1681[64];
db dummy1682[64];
db dummy1683[64];
db hazard_bonus[46];
db dummy1684[53];
dd viseur_hazard_bonus;
db hazard_bonus2[8];
db dummy1685[8];
dd viseur_hazard_bonus2;
db correspondance_bonus[16];
db correspondance_bonus2[16];
db couleur[8];
db couleur_menu[8];
db scrolly[1968];
db last_sucker;
db pal[768];
db pal_affiche[768];
db affiche_pal;
db hazard_maladie[8];
db dummy1686[8];
db pause;
db pause2;
db _setup_;
db setup_wait2;
db setup_wait3;
db setup_wait4;
dd setup_viseur;
dd setup_viseur2;
dw setup_viseur2_offset[9];
dd ou_ca_setup;
dd viseur_rouge3[2];
dd dummy1687[2];
dd dummy1688[2];
dd dummy1689[2];
dd dummy1690[2];
dd dummy1691[2];
dd dummy1692[2];
dd dummy1693[2];
dd dummy1694[2];
dd viseur_rouge[2];
dd dummy1695[2];
dd dummy1696[2];
dd dummy1697[2];
dd dummy1698[2];
dd dummy1699[2];
dd dummy1700[2];
dd dummy1701[2];
dd dummy1702[2];
dd dummy1703[2];
dd dummy1704[2];
dd dummy1705[2];
dd dummy1706[2];
dd dummy1707[2];
dd dummy1708[2];
dd dummy1709[2];
dd dummy1710[2];
dd viseur_rouge2[2];
dd dummy1711[2];
dd dummy1712[2];
dd dummy1713[2];
dd dummy1714[2];
dd dummy1715[2];
dd dummy1716[2];
db what_t[17];
db _setup_wait;
db temps2;
db liste_terrain[9];
db sortie;
db sortie_config;
db lost_conney;
db in_the_apocalypse;
db invite_recu;
db ascii[11];
db dummy1717;
db dummy1718;
db dummy1719;
db enddata;

dd eax;
dd ebx;
dd ecx;
dd edx;
dd esi;
dd edi;
dd ebp;
dd esp;
dw cs;
dw ds;
dw es;
dw fs;
dw gs;
dw ss;
_Bool CF;
_Bool ZF;
_Bool DF;
_Bool SF;
_Bool jumpToBackGround;
_Bool executionFinished;
db exitCode;
db vgaPalette[256*3];
int stackPointer;
dd stack[STACK_SIZE];
dd selectorsPointer;
dd selectors[NB_SELECTORS];
dd heapPointer;
db heap[HEAP_SIZE];
db vgaRam0[VGARAM_SIZE];
db vgaRam[VGARAM_SIZE];
db vgaRam2[VGARAM_SIZE];
char *path;
} Memory;
int program();
#endif



#define sizeOfeax 4
#define sizeOfebx 4
#define sizeOfecx 4
#define sizeOfedx 4
#define sizeOfesi 4
#define sizeOfedi 4
#define sizeOfebp 4
#define sizeOfesp 4
#define sizeOfcs 2
#define sizeOfds 2
#define sizeOfes 2
#define sizeOffs 2
#define sizeOfgs 2
#define sizeOfss 2
#define sizeOfliste_de_machin  4
#define sizeOftrucs  1
#define sizeOfbeginningdata  1
#define sizeOftaille_exe_gonfle  4
#define sizeOfplaysoundfx  1
#define sizeOfbuffer  1
#define sizeOfmaster  1
#define sizeOfclavier  1
#define sizeOfclavier_stuff  1
#define sizeOfclavier_stuff2  1
#define sizeOfclavier_extanded  1
#define sizeOfpal_pic  1
#define sizeOfpal_pic2  1
#define sizeOfpal_jeu  1
#define sizeOfpal_med  1
#define sizeOfpal_vic  1
#define sizeOfpal_draw  1
#define sizeOfwinhdle  4
#define sizeOfvise_de_ca_haut  4
#define sizeOfvise_de_ca_haut2  4
#define sizeOfadder_inser_coin  4
#define sizeOfoffset_ic  4
#define sizeOfviseur_ic2  4
#define sizeOfinser_coin  4
#define sizeOfstat_ou_pas  4
#define sizeOfacceleration  4
#define sizeOfattente_entre_chake_bombe  4
#define sizeOfnouvelle_attente_entre_chake_bombe2  4
#define sizeOfviseur__nouvelle_attente_entre_chake_bombe  4
#define sizeOfliste_bombbbb  4
#define sizeOfliste_bombbbb2  4
#define sizeOfspecial_nivo_6  4
#define sizeOfdifferentesply  4
#define sizeOfdifferentesply2  4
#define sizeOftemps_avant_demo  4
#define sizeOftouches_  4
#define sizeOfspecial_clignotement  4
#define sizeOfnuage_sympa  4
#define sizeOfarbre  4
#define sizeOfviseur_couleur  4
#define sizeOflast_voice  4
#define sizeOfmonstro  4
#define sizeOfattente_nouveau_esc  4
#define sizeOfscrollyf  4
#define sizeOftecte2  4
#define sizeOfpackets_jeu_envoyes  4
#define sizeOfpackets_jeu_recus  4
#define sizeOfkb_packets_jeu_envoyes  4
#define sizeOfadder_speciale_cfg_path  4
#define sizeOfwindows  4
#define sizeOfoffset_pause  4
#define sizeOfoffset_si  4
#define sizeOfmax_lost  4
#define sizeOfmax_lost_master  4
#define sizeOfmax_lost_master2  4
#define sizeOfnew_lost  4
#define sizeOfloaded_f  1
#define sizeOfnombre_de_dyna_x4  4
#define sizeOfchangeiny  4
#define sizeOfviseur_change_in  4
#define sizeOfviseur_change_in_save  4
#define sizeOfanti_bomb  4
#define sizeOfmachin2  4
#define sizeOfmachin3  4
#define sizeOfmachin  4
#define sizeOfrien_recu  4
#define sizeOfload_pcx_interne  4
#define sizeOfsuper_signe2  4
#define sizeOfduree_draw  4
#define sizeOfduree_med  4
#define sizeOfduree_vic  4
#define sizeOfaffiche_raster  4
#define sizeOfsave_banke  4
#define sizeOfkezax  4
#define sizeOfattente_avant_draw  4
#define sizeOfattente_avant_med  4
#define sizeOfload_handle  4
#define sizeOfpic_time  4
#define sizeOfadresse_des_fonds  4
#define sizeOfadresse_des_fonds_foot  4
#define sizeOfadresse_des_fonds_neige  4
#define sizeOfadresse_des_fonds_final  4
#define sizeOfadresse_des_fonds_foret  4
#define sizeOfadresse_des_fonds_nuage  4
#define sizeOfadresse_des_fonds_crayon  4
#define sizeOfadresse_des_fonds_soccer  4
#define sizeOfnombre_de_fond  4
#define sizeOfviseur_sur_fond  4
#define sizeOfadresse_des_draws  4
#define sizeOfnombre_de_draw  4
#define sizeOfviseur_sur_draw  4
#define sizeOfadresse_des_vic  4
#define sizeOfnombre_de_vic  4
#define sizeOfviseur_sur_vic  4
#define sizeOfattente  4
#define sizeOfkelle_donnee  4
#define sizeOfkelle_fin  4
#define sizeOfkelle_truc  4
#define sizeOfkelle_bonus  4
#define sizeOfkelle_apocalypse  4
#define sizeOfkelle_duree  4
#define sizeOfoffset_briques  2
#define sizeOfkelle_offset_fond  4
#define sizeOfkel_viseur_brike_fin  2
#define sizeOflapin_mort  2
#define sizeOflapin_mortg  2
#define sizeOflapin2  2
#define sizeOflapin2g  2
#define sizeOflapin2___  2
#define sizeOflapin2___g  2
#define sizeOflapin2_  2
#define sizeOflapin2_g  2
#define sizeOflapin2__  2
#define sizeOflapin2__g  2
#define sizeOfgrosbleu  2
#define sizeOfcoca  2
#define sizeOfescargot  2
#define sizeOfold_school  2
#define sizeOfbleu_triste  2
#define sizeOfmachine  2
#define sizeOfpetit_jaune  2
#define sizeOfblanc  2
#define sizeOfbleu  2
#define sizeOfrouge  2
#define sizeOfvert  2
#define sizeOfblancg  2
#define sizeOfbleug  2
#define sizeOfrougeg  2
#define sizeOfvertg  2
#define sizeOfcompteur_nuage  4
#define sizeOfchangementzz  4
#define sizeOfchangementzz2  4
#define sizeOfchangement  4
#define sizeOftruc  1
#define sizeOftruc2  1
#define sizeOftruc_x  1
#define sizeOftruc_y  1
#define sizeOftruc_monstre  1
#define sizeOfcentral_b  2
#define sizeOftouches  4
#define sizeOfavance  4
#define sizeOfavance2  4
#define sizeOftouches_save  4
#define sizeOfaction  1
#define sizeOfvie  4
#define sizeOfvictoires  4
#define sizeOflatest_victory  4
#define sizeOfteam  4
#define sizeOfnombre_minimum_de_dyna  4
#define sizeOfn_team  4
#define sizeOfc_team  4
#define sizeOfs_team  4
#define sizeOfviseur_victory  4
#define sizeOfviseur_victoryc  4
#define sizeOfviseur_victoryg  4
#define sizeOfviseur_name  4
#define sizeOfviseur_namec  4
#define sizeOfviseur_nameg  4
#define sizeOfoffset_medaille  2
#define sizeOfinfos_j_n  4
#define sizeOfinfos_m_n  4
#define sizeOfrandom_place  4
#define sizeOflast_bomb  4
#define sizeOfinfojoueur  4
#define sizeOfinfojoueur2  4
#define sizeOfj1  4
#define sizeOfj2  4
#define sizeOfj3  4
#define sizeOfj4  4
#define sizeOfj5  4
#define sizeOfj6  4
#define sizeOfj7  4
#define sizeOfj8  4
#define sizeOfliste_bombe  4
#define sizeOfdonnee  2
#define sizeOfooo546  4
#define sizeOfliste_couleur  4
#define sizeOfnombre_de_coups  4
#define sizeOfclignotement  4
#define sizeOfpousseur  4
#define sizeOfpatineur  4
#define sizeOfvitesse_monstre  4
#define sizeOftribombe2  4
#define sizeOftribombe  4
#define sizeOfinvinsible  4
#define sizeOfblocage  4
#define sizeOflapipipino  4
#define sizeOflapipipino2  4
#define sizeOflapipipino3  4
#define sizeOflapipipino4  4
#define sizeOflapipipino5  4
#define sizeOflapipipino6  4
#define sizeOflapipipino7  4
#define sizeOfdonnee4  1
#define sizeOfviseur_liste_terrain  4
#define sizeOfnombre_de_dyna  4
#define sizeOfaction_replay  1
#define sizeOfnombre_de_monstres  4
#define sizeOfnombre_de_vbl_avant_le_droit_de_poser_bombe  4
#define sizeOfordre2  1
#define sizeOfspeed_raster  1
#define sizeOfdetail  1
#define sizeOfmechant  1
#define sizeOfterrain  1
#define sizeOfteam3  1
#define sizeOfpauseur2  1
#define sizeOftemps  2
#define sizeOfbdraw666  1
#define sizeOfadder_bdraw  2
#define sizeOfblow_what2  2
#define sizeOfblow_what  2
#define sizeOfkel_ombre  4
#define sizeOfombres  2
#define sizeOfbriques  2
#define sizeOfbombes  2
#define sizeOfbuffer_vide  1
#define sizeOfmax_packet  4
#define sizeOfliste_couleur_malade  4
#define sizeOfcontrol_joueur  4
#define sizeOfcontrol_joueur2  4
#define sizeOfname_joueur  4
#define sizeOftemps_joueur  4
#define sizeOfliste_adresse  1
#define sizeOfnb_ordy_connected  4
#define sizeOflast_packet_size  4
#define sizeOfadresse_master  1
#define sizeOflast_name  4
#define sizeOftotal_play  1
#define sizeOftotal_t  1
#define sizeOfdonnee2  1
#define sizeOfdonnee98  1
#define sizeOfmenu_  1
#define sizeOfgame_  1
#define sizeOfdemo_  1
#define sizeOfwarning_ipx  1
#define sizeOfwarning_ipx2  1
#define sizeOfwarning_ipx3  1
#define sizeOfno_dyna  1
#define sizeOfno_dyna2  1
#define sizeOfpas_de_mem  1
#define sizeOfpbs1  1
#define sizeOfpbs2  1
#define sizeOfsocketipx  1
#define sizeOferreur_dans_ecoute2  1
#define sizeOfinformation  1
#define sizeOfpasipx  1
#define sizeOfmsg1  1
#define sizeOfmsg2  1
#define sizeOfmsg3  1
#define sizeOfmsg4  1
#define sizeOfnomdetriche  1
#define sizeOfnomdetriche2  1
#define sizeOfipx  1
#define sizeOfloaderror  1
#define sizeOfbusy  1
#define sizeOfbusy2  1
#define sizeOfversion2  1
#define sizeOfversion2b  1
#define sizeOferreur3  1
#define sizeOfohohohohoh  1
#define sizeOfkill  1
#define sizeOftected  1
#define sizeOftecte  1
#define sizeOfmessage1  1
#define sizeOfmessage2  1
#define sizeOfmessage3  1
#define sizeOfmess_kli  1
#define sizeOfmess_luc  1
#define sizeOfmess_frd  1
#define sizeOfmess_jag  1
#define sizeOfmess_din  1
#define sizeOfmess_jdg  1
#define sizeOfmess_rmd  1
#define sizeOfmess_kor  1
#define sizeOfmess_sl1  1
#define sizeOfmess_adr  1
#define sizeOfmess_wil  1
#define sizeOfmess_exo  1
#define sizeOfmess_cl  1
#define sizeOfmess_ben  1
#define sizeOfmess_aaa  1
#define sizeOfmess_fzf  1
#define sizeOfmess_het  1
#define sizeOfmess_big  1
#define sizeOfmess_hak  1
#define sizeOfmess_jc  1
#define sizeOfdefo  1
#define sizeOfintro_txt  1
#define sizeOfnick_t  1
#define sizeOflove_si  1
#define sizeOfrmd_file_name  1
#define sizeOfiff_file_name  1
#define sizeOfwinsux  1
#define sizeOfpas_ligne  1
#define sizeOfinfo666  1
#define sizeOfpathing  1
#define sizeOfsetup_  1
#define sizeOfsetup_k  1
#define sizeOfsetup_e  1
#define sizeOfsetup_m  1
#define sizeOfsetup_w  1
#define sizeOfsetup_d  1
#define sizeOfsetup_3  1
#define sizeOfsetup_t  1
#define sizeOfsetup_f  1
#define sizeOfsetup_b  1
#define sizeOfsetup_2  1
#define sizeOfsetup_n  1
#define sizeOfsetup_x  1
#define sizeOfsetup_c  1
#define sizeOfsetup_s  1
#define sizeOfsetup_l  1
#define sizeOfsetup_n_error  1
#define sizeOftest1  1
#define sizeOfnom_terrain  1
#define sizeOfcfgfile  1
#define sizeOfcfgfile2  1
#define sizeOfreccord  1
#define sizeOfreccord3  1
#define sizeOfreccord2  1
#define sizeOfsuite  1
#define sizeOfsuite2  1
#define sizeOfsuite3  1
#define sizeOfcfgerror  1
#define sizeOferrorcfg  1
#define sizeOfmessage_mem_rp  1
#define sizeOfokcfg  1
#define sizeOfokcfg3  1
#define sizeOfwin  1
#define sizeOfnowin  1
#define sizeOfterminalor  1
#define sizeOfnulosproduction  1
#define sizeOfstat1  1
#define sizeOfstat2  1
#define sizeOfstat3  1
#define sizeOfgameover  1
#define sizeOfno_server_  1
#define sizeOfselect_server_  1
#define sizeOfcnx1  1
#define sizeOftransformateur_98  1
#define sizeOfcnx2  1
#define sizeOfnotreadresse  1
#define sizeOftoutes_adresse  1
#define sizeOfecb1  4
#define sizeOfheader_ecoute  2
#define sizeOfecb3  4
#define sizeOfheader_ecoute3  2
#define sizeOfrecu_data  1
#define sizeOfrecu_data3  1
#define sizeOfpacked_data  1
#define sizeOfdonnee3  1
#define sizeOfenvoye_data  1
#define sizeOfcall_int  4
#define sizeOfdifferents_offset_possible  4
#define sizeOfpacked_liste  4
#define sizeOftotal_liste  4
#define sizeOfiff_liste  4
#define sizeOflapin_mania  4
#define sizeOflapin_mania_malade  4
#define sizeOflapin_mania1  4
#define sizeOflapin_mania2  4
#define sizeOflapin_mania3  4
#define sizeOflapin_mania4  4
#define sizeOflapin_mania5  4
#define sizeOfdonnee_s  2
#define sizeOfooo34  4
#define sizeOfdonnee_foot  2
#define sizeOfdonnee_soccer  2
#define sizeOfdonnee_h  2
#define sizeOfdonnee_n  2
#define sizeOfdonnee_c  2
#define sizeOfdonnee_f  2
#define sizeOfdonnee_s_neige  2
#define sizeOfliste_couleur_normal  4
#define sizeOfs_normal  4
#define sizeOfl_normal  2
#define sizeOfc_normal  2
#define sizeOfa_normal  4
#define sizeOfr_normal  4
#define sizeOftruc_fin  1
#define sizeOftruc_fin_s  1
#define sizeOftruc_fin_soccer  1
#define sizeOftruc_fin_s_c  1
#define sizeOftruc_fin_s_m  1
#define sizeOftruc_fin_s_n  1
#define sizeOftruc_s  1
#define sizeOftruc_foot  1
#define sizeOftruc_soccer  1
#define sizeOftruc_n  1
#define sizeOftruc_c  1
#define sizeOftruc_h  1
#define sizeOftruc_f  1
#define sizeOftruc_neige  1
#define sizeOftruc2_save_foot  1
#define sizeOftruc2_save  1
#define sizeOftruc2_save_n  1
#define sizeOfia  4
#define sizeOfordre  1
#define sizeOffx  2
#define sizeOftexte1  1
#define sizeOfpanning2  1
#define sizeOfmaladie  4
#define sizeOfoffset_oiseau  4
#define sizeOflost_msg  2
#define sizeOfgrosse_sochette  2
#define sizeOfmort_de_lapin  2
#define sizeOfsaut_de_lapin2  2
#define sizeOfsaut_de_lapin  2
#define sizeOfsave64  1
#define sizeOfwindowsnetwork  1
#define sizeOfeconomode  1
#define sizeOfdemande_partie_slave  1
#define sizeOfdemande_partie_slave2  1
#define sizeOfkli_option  1
#define sizeOfbalance_le_bdrawn  1
#define sizeOfbdraw1  1
#define sizeOfon_a_bien_fait_une_partie  1
#define sizeOfon_les_dans_le_menu  1
#define sizeOfsortie_slave  1
#define sizeOfmodeinfo  1
#define sizeOfwillrecord  1
#define sizeOfnomonster  1
#define sizeOftwice  1
#define sizeOftwice2  1
#define sizeOfoffset_fille  2
#define sizeOfoffset_supporter  1
#define sizeOfoffset_cameraman  1
#define sizeOfpic_de_tout_debut  1
#define sizeOfune_touche_a_telle_ete_pressee  1
#define sizeOfsors_du_menu_aussitot  1
#define sizeOfteam3_sauve  1
#define sizeOfspecial_on_a_loadee_nivo  1
#define sizeOfrecord_user  1
#define sizeOfprevientlmesenfants  1
#define sizeOfcouleurssss  1
#define sizeOfhazard_bonus  1
#define sizeOfviseur_hazard_bonus  4
#define sizeOfhazard_bonus2  1
#define sizeOfviseur_hazard_bonus2  4
#define sizeOfcorrespondance_bonus  1
#define sizeOfcorrespondance_bonus2  1
#define sizeOfcouleur  1
#define sizeOfcouleur_menu  1
#define sizeOfscrolly  1
#define sizeOflast_sucker  1
#define sizeOfpal  1
#define sizeOfpal_affiche  1
#define sizeOfaffiche_pal  1
#define sizeOfhazard_maladie  1
#define sizeOfpause  1
#define sizeOfpause2  1
#define sizeOf_setup_  1
#define sizeOfsetup_wait2  1
#define sizeOfsetup_wait3  1
#define sizeOfsetup_wait4  1
#define sizeOfsetup_viseur  4
#define sizeOfsetup_viseur2  4
#define sizeOfsetup_viseur2_offset  2
#define sizeOfou_ca_setup  4
#define sizeOfviseur_rouge3  4
#define sizeOfviseur_rouge  4
#define sizeOfviseur_rouge2  4
#define sizeOfwhat_t  1
#define sizeOf_setup_wait  1
#define sizeOftemps2  1
#define sizeOfliste_terrain  1
#define sizeOfsortie  1
#define sizeOfsortie_config  1
#define sizeOflost_conney  1
#define sizeOfin_the_apocalypse  1
#define sizeOfinvite_recu  1
#define sizeOfascii  1
#define sizeOfenddata  1
