.TH mrboom 6 "March 27 2017"
.SH NAME
mrboom \- 8 players Bomberman
.SH SYNOPSIS
.B mrboom
.RI [ options ] " files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B mrboom
command.
.PP
\fBmrboom\fP is an SDL2 version of the original 1999 version of Mr. Boom
.SH USAGE
The goal of the game is to bomb away your enemies and other players.
Bomberman is controlled with the keyboard.
.IP "Keys"
Left - Left
.br
Right - Right
.br
Up - Up
.br
Down - Down
.br
Ctrl - Lay bomb
.br
Alt - Ignite bomb
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
