.TH mrboom 6 "January 14 2019"
.SH NAME
mrboom \- 8 player Bomberman
.SH SYNOPSIS
.B mrboom
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B mrboom
command.
.PP
\fBmrboom\fP is an SDL2 version of the original 1999 version of Mr.Boom
.SH USAGE
The goal of the game is to bomb away your enemies and other players.
Bomberman is controlled with the keyboard or with (up to 8) joypads.
.IP "Keys"
Space - Add a bomberman bot
.br
Return - Start a game
.br
P or Pause/Break - Pause
.br
ESC - Quit
.IP "1st player"
Left - Left
.br
Right - Right
.br
Up - Up
.br
Down - Down
.br
Right Ctrl, End, Keypad 0, Right GUI (Windows) or Right Command (Apple) - Lay bomb
.br
Right Alt, Keypad Dot or PageDown - Ignite bomb
.br
Right Shift, Keypad Enter or Home - Jump
.IP "2nd player"
A - Left
.br
D - Right
.br
W - Up
.br
S - Down
.br
Left Ctrl, Left GUI (Windows) or Left Command (Apple) - Lay bomb
.br
Left Alt - Ignite bomb
.br
Left Shift - Jump
.SH OPTIONS
.TP
.B \-f, \-\-fx <x>
FX volume: with <x> from 0 to 10. 
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-m, \-\-nomonster
No monster mode.
.TP
.B \-s, \-\-sex
Sex team mode.
.TP
.B \-c, \-\-color
Color team mode.
.TP
.B \-k, \-\-skynet
Humans vs. machines mode.
.TP
.B \-n, \-\-noautofire
No autofire for bomb drop.
.TP
.B \-d, \-\-deadzone <x>
Set joysticks dead zone, default is 8000.
.TP
.B \-z, \-\-nomusic
No music.
.TP
.B \-v, \-\-version
Show version of program.

